### ISSUE TITLE
input data quality and internal consistency checks

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#10]
- [ ] column names
- [ ] data types

**Comment by akey7** [comment]
Moving to the backlog. I removed items that are obsolete and have been solved with further code developments since I created this issue. While it would be a nice user experience to run checks on all the files before the model execution, this is not required since the exceptions thrown yield information on what needs to be fixed.

**Comment by rjhanes** [comment]
Good point @akey7  on the exceptions, and thank you for reviewing. I'm going to close this issue just because I doubt this will be a priority through the end of the FY, and if the project continues we'll likely be focusing on functionality development rather than user experience.
