### ISSUE TITLE
add warning in pylca_opt_foreground when processes are removed from the foreground inventory

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#110]

**Comment by TJTapajyoti** [comment]
The pylca_opt_foreground file does not remove flows from the process inventory. The comment was copied from the pylca background file where actually dummy flows are removed such that the X matrix does not have such flows. A dataframe is created in the listing the dummy flows. 

In pylca_opt_foreground there is no chance of creation of such dummy flows because all flows which are not products end up outside the X matrix. The inventory file is setup in such a fashion there is no chance of dummy flows. There can only be inputs and outputs. Inputs are separated out of the outputs and then the technology matrix is created. If for some reason, there are flows in the foreground lca inventory which do not exist in the USLCI, those flows are just not included in the final demand matrix in the pylca_opt_background calculations.

I am removing the comment and making necessary corrections. The warning is thus unnecessary
