### ISSUE TITLE
oaat runs 5, 6 and 17 throwing error. Seems like yaml error.

### ISSUE THREAD

**Issue by TJTapajyoti** [NREL/celavi#178]
Traceback (most recent call last):
  File "__main__.py", line 25, in <module>
    Scenario(parser=PARSER)
  File "/lustre/eaglefs/projects/celavi/celavi/celavi/celavi/scenario.py", line 99, in __init__
    self.setup()
  File "/lustre/eaglefs/projects/celavi/celavi/celavi/celavi/scenario.py", line 249, in setup
    self.netw = CostGraph(
  File "/lustre/eaglefs/projects/celavi/celavi/celavi/celavi/costgraph.py", line 143, in __init__
    self.build_supplychain_graph()
  File "/lustre/eaglefs/projects/celavi/celavi/celavi/celavi/costgraph.py", line 723, in build_supplychain_graph
    self.supply_chain.edges[edge]["cost"] = sum(
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by rjhanes** [comment]
I haven't made any changes to 5_rtm_oaat.yaml, 6_rtb_oaat.yaml or 17_fgl_oaat.yaml since the last set of runs. There's nothing obviously wrong with the structure of any of them, and 5 and 6 were previously executing correctly, so I'll need to debug for a bit to figure out what's going on.

Questions:
(1) Is the same line throwing the same error for all three scenarios?
(2) Has scenario 17_fgl_oaat executed correctly at all since commit [5626f59](https://github.com/NREL/celavi/commit/5626f59d4c498200dee1fab09ca3e082a92e942f)?

**Comment by rjhanes** [comment]
I'm unable to reproduce any kind of error running scenario 17_fgl_oaat.yaml (adapted for tiny-data: no location filtering, using fake capacity expansion dataset) on commit [acae063](https://github.com/NREL/celavi/commit/acae063f792671d79072b3d62d890cd8928e377d) and tiny data commit [465c78f](https://github.nrel.gov/rhanes/celavi-data/commit/465c78f2d263229983043dba94f8034d764aa80f). I checked the diagnostic plots and everything looks like I would expect it to.

@TJTapajyoti I'm guessing you're executing runs on the `pylca2.0-upgrade` branch instead of `develop`? That branch doesn't have the fix for issue #175 and I suspect that's the problem here. Please merge in PR #176 to `develop` and test again using `develop`. In the future please only use `develop` (or `main`, if it was recently released) to get official results.

**Comment by TJTapajyoti** [comment]
Resolved! Thank you. The 17 was due to the wrong branch being used.
