### ISSUE TITLE
Isolation of transportation tracker for HPC speed debugging

### ISSUE THREAD

**Issue by TJTapajyoti** [NREL/celavi#27]
**Issue explored** - Cause of significant slow down for HPC runs. 

**How** - Starting with Aug 18th repo version, the data and the code repo was updated step by step to **isolate transportation tracker as the main cause of the slowdown.** 

_The latest version of the code without transportation tracker is housed in [this branch](https://github.com/NREL/celavi/tree/hpc_speed_debug)

**Differences -** 

**Data repository** - The version of the data repository that is currently working is[ this. ](https://github.nrel.gov/akey/celavi-data/tree/september-8-tj-branch) Due to issues in the current commit to the data repo, this version was used in the HPC runs. _Its from Sep 8 before the harmonization commits_. 

**Code repository -** 

The differences in the code repository are highlighted in this [pull request. ](https://github.com/NREL/celavi/pull/26/files)
1. __main.py__ has no significant changes. Minor changes. (Please ignore)
2. costgraph.py has changes. Not sure if this is related to transportation tracker. Using this version without the transportation tracker files and commits resulted in runtime errors. So I am guessing its linked. @rjhanes Need your help on this
![image](https://user-images.githubusercontent.com/24482959/132925578-783f9e95-5b3b-465b-b1cc-a2a35a4f73c0.png) 
3. des.py and component.py has major changes - Transportation tracker. @akey7 Need your help on this. 

**Way forward -** 
This is my suggestion. Please feel free to suggest different ways - 

Update the hpc_speed_debug with the addition of the transportation tracker step by step such that we can isolate the slow down issue.  
Have a session where we work on this. I will not recommend a live session because re initializing cost graph and running takes time. However, CO and OH ( A combination of states) that I found to have low turbines and all possible facilities might be a good one to help debug this issue if we have a live session.

**Comment by rjhanes** [comment]
I don't think we'll be able to add the transportation tracker "step by step" because I suspect it'll only run if all part of the tracker code are there.

Instead, I'd suggest adding some debugging statements to time the new lines in CostGraph, maybe on the LCIA side of the model, and where possible in the DES model (thinking component initialization, particularly) so we get a feel for how long each part of the code takes to execute. 

Once we have that information, I agree we should go over this in the next hackathon or in a separate meeting.

And a final thought - if it is the DES portion of the model that's slowing the runs down, we can always change to modeling all blades for a turbine as one massive blade with three times the mass. That will reduce the complexity of the DES model to a third of what it is now without changing any of the results.

**Comment by TJTapajyoti** [comment]
> I don't think we'll be able to add the transportation tracker "step by step" because I suspect it'll only run if all part of the tracker code are there.
> 
> Instead, I'd suggest adding some debugging statements to time the new lines in CostGraph, maybe on the LCIA side of the model, and where possible in the DES model (thinking component initialization, particularly) so we get a feel for how long each part of the code takes to execute.
> 
> Once we have that information, I agree we should go over this in the next hackathon or in a separate meeting.
> 
> And a final thought - if it is the DES portion of the model that's slowing the runs down, we can always change to modeling all blades for a turbine as one massive blade with three times the mass. That will reduce the complexity of the DES model to a third of what it is now without changing any of the results.

Is the costgraph.py changes highlighted here part of the transportation tracker?

**Comment by rjhanes** [comment]
@TJTapajyoti The `CostGraph` changes highlighted here are required for the transportation tracker to run.

**Comment by TJTapajyoti** [comment]
Issue has been resolved for now. Closing issue.
